name: bluetooth_printing_test
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.4 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  printing: ^5.9.3
  pdf: ^3.8.4
  intl: ^0.17.0
  geolocator: ^9.0.2
  flutter_easyloading: ^3.0.5
  rename: ^2.0.1
  bluetooth_print: ^4.3.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

