name: bluetooth_printing_test
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.5 <=4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  printing: ^5.11.1
  pdf: ^3.8.4
  intl: ^0.17.0
  geolocator: ^9.0.2
  flutter_easyloading: ^3.0.5
  rename: ^2.0.1
  bluetooth_print: ^4.3.0
  whatsapp_share: ^2.0.2
  whatsapp_unilink: ^2.1.0
  url_launcher: ^6.1.7
  fluttercontactpicker: ^4.7.0
  permission_handler: ^10.2.0
  contacts_service: ^0.6.3
  get: ^4.6.5
  blue_thermal_printer: ^1.2.3
  get_storage: ^2.0.3
  print_bluetooth_thermal: 1.0.9
  esc_pos_utils_plus: 2.0.3
  image: 4.1.3
  modal_bottom_sheet: ^3.0.0-pre
  shimmer: 3.0.0
  app_settings: 5.1.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
  uses-material-design: true

